//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ps.Iso.Viewer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ps.Iso.Viewer.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string EditValueDialog_InitializeComponent_btCancel {
            get {
                return ResourceManager.GetString("EditValueDialog_InitializeComponent_btCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string EditValueDialog_InitializeComponent_OK {
            get {
                return ResourceManager.GetString("EditValueDialog_InitializeComponent_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование поля.
        /// </summary>
        internal static string EditValueDialog_InitializeComponent_Text {
            get {
                return ResourceManager.GetString("EditValueDialog_InitializeComponent_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to файлы ISO|*.iso|Все файлы|*.*.
        /// </summary>
        internal static string IsoFileFilter {
            get {
                return ResourceManager.GetString("IsoFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверить на ошибки....
        /// </summary>
        internal static string IsoFileForm__miCheckFile_Text {
            get {
                return ResourceManager.GetString("IsoFileForm__miCheckFile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть ISO-файл.
        /// </summary>
        internal static string IsoFileForm_Init_btnOpenIsoFile_Text {
            get {
                return ResourceManager.GetString("IsoFileForm_Init_btnOpenIsoFile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        internal static string IsoFileForm_Init_menuExit_Text {
            get {
                return ResourceManager.GetString("IsoFileForm_Init_menuExit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О программе.
        /// </summary>
        internal static string IsoFileForm_Init_miAbout_Text {
            get {
                return ResourceManager.GetString("IsoFileForm_Init_miAbout_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Быстрое редактирование.
        /// </summary>
        internal static string IsoFileForm_Init_miEditOnEnter_Text {
            get {
                return ResourceManager.GetString("IsoFileForm_Init_miEditOnEnter_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справка.
        /// </summary>
        internal static string IsoFileForm_Init_miHelp_Text {
            get {
                return ResourceManager.GetString("IsoFileForm_Init_miHelp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string IsoFileForm_Init_miSave_Text {
            get {
                return ResourceManager.GetString("IsoFileForm_Init_miSave_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить как....
        /// </summary>
        internal static string IsoFileForm_Init_miSaveAs_Text {
            get {
                return ResourceManager.GetString("IsoFileForm_Init_miSaveAs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить в формате RDF....
        /// </summary>
        internal static string IsoFileForm_Init_miSaveAsRdf_Text {
            get {
                return ResourceManager.GetString("IsoFileForm_Init_miSaveAsRdf_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать шрифт....
        /// </summary>
        internal static string IsoFileForm_Init_miSelectFont_Text {
            get {
                return ResourceManager.GetString("IsoFileForm_Init_miSelectFont_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотреть схему....
        /// </summary>
        internal static string IsoFileForm_Init_miShowScheme_Text {
            get {
                return ResourceManager.GetString("IsoFileForm_Init_miShowScheme_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открытие файла.
        /// </summary>
        internal static string IsoFileForm_Init_openFileDialog_Title {
            get {
                return ResourceManager.GetString("IsoFileForm_Init_openFileDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид.
        /// </summary>
        internal static string IsoFileForm_Init_viewMenuItem_Text {
            get {
                return ResourceManager.GetString("IsoFileForm_Init_viewMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кнопка &quot;Открыть ISO-файл&quot;.
        /// </summary>
        internal static string IsoFileForm_Init_Кнопка_miShowOpenIsoFileButton_Text {
            get {
                return ResourceManager.GetString("IsoFileForm_Init_Кнопка_miShowOpenIsoFileButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to файлы ISO|*.iso|Все файлы|*.*.
        /// </summary>
        internal static string IsoFileForm_Init_файлы_ISO_openFileDialog_Filter {
            get {
                return ResourceManager.GetString("IsoFileForm_Init_файлы_ISO_openFileDialog_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменения не были сохранены. Вы действительно хотите выйти?.
        /// </summary>
        internal static string IsoFileForm_IsoFileForm_FormClosing_UnsavedChanges {
            get {
                return ResourceManager.GetString("IsoFileForm_IsoFileForm_FormClosing_UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предупреждение.
        /// </summary>
        internal static string IsoFileForm_IsoFileForm_FormClosing_Warning {
            get {
                return ResourceManager.GetString("IsoFileForm_IsoFileForm_FormClosing_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый файл.
        /// </summary>
        internal static string IsoFileForm_IsoFileForm_NewFile {
            get {
                return ResourceManager.GetString("IsoFileForm_IsoFileForm_NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to файлы RDF|*.rdf|Все файлы|*.*.
        /// </summary>
        internal static string IsoFileForm_miSaveAsRdf_Click_Filename_Filter {
            get {
                return ResourceManager.GetString("IsoFileForm_miSaveAsRdf_Click_Filename_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string IsoFileForm_PrintError_Error {
            get {
                return ResourceManager.GetString("IsoFileForm_PrintError_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет разрешения на доступ к файлам. Возможно, это вызвано тем, что приложение запущено с сетевого диска. Попробуйте запустить приложение с локального диска..
        /// </summary>
        internal static string IvApplication_Main_NoAcces {
            get {
                return ResourceManager.GetString("IvApplication_Main_NoAcces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение перезаписи.
        /// </summary>
        internal static string SaveIsoDialog_btSave_OverwriteCaption {
            get {
                return ResourceManager.GetString("SaveIsoDialog_btSave_OverwriteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Указанный файл уже существует. Заменить?.
        /// </summary>
        internal static string SaveIsoDialog_btSave_OverwriteMessage {
            get {
                return ResourceManager.GetString("SaveIsoDialog_btSave_OverwriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string StrError {
            get {
                return ResourceManager.GetString("StrError", resourceCulture);
            }
        }
    }
}
